### ISSUE TITLE
Bridgy support in v2.0.1

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#10]
Before I update, I notice that v2.0.1 indicates:
* Bridgy Support removed - new Bridgy plugin will handle that

Does this mean that the new Bridgy plugin already exists and is currently handling Bridgy support? 

Is this plugin within syndication-links, or a separate project within Indie Web? If it's in syndication-links does this mean that I'll be without bridgy support until the next update?

Thanks, as always, David for you work on this and the indieweb movement!

**Comment by dshanske** [comment]
This is Bridgy Publish support. Not Bridgy support in general. I should be more specific.

The Syndication Links, which Bridgy pulls for POSSE post discovery aren't changing. This is the code that got those links from Bridgy Publish.

https://github.com/dshanske/bridgy-publish is something I bumped up over the last day to POSSE using Bridgy. It's waiting for repository approval.
