### ISSUE TITLE
SVG images vs sprites

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#100]
I'm coming around to the idea that SVGs should be added individually. Having looked at the Simple Icons library of images, I probably wouldn't use 98% of these on my site for the foreseeable future. I imagine many or most people using this plugin fall in a similar category.

We're paying a price of downloading a >600KB sprite + ~22KB CSS file with colors. Even if a WordPress install is using compression and caching, these still is more than 200KB of loading + the rest of the page.

I like Sprites and think they're generally a good way to go but none of this works in Internet Explorer if that's a thought. I also think the massive size of a file that's likely to only ~1% useful to people should be considered.

While I think added HTTP requests are not a good thing, I think the size of the individual SVGs is a better choice for syndication link icons on posts. HTTP2+ will also help with asynchronous loading of these smaller SVG files.

The one problem I didn't account for yet is how to include ONLY the CSS fill colors for the corresponding individual SVGs. Maybe creating a smaller CSS file with only the most popular social networks to syndicate to? Hard to say

**Comment by dshanske** [comment]
The 2019 theme uses inline svg. Wonder if we should try that.

**Comment by asuh** [comment]
Interesting, I didn't know that. I think it's the best choice if it's possible. I also think they have a decent set of icons in that SVG class file, minus a few like Google+ which is effectively dead. And then adding a few like Mastodon, Micro.blog, Known, Pixelfed, and other open source solutions.

Including a link to the CSS hex colors via an alternative CSS file (that would include all the base Syndication Links styling) could also work, where you enable it in the Dashboard settings page. Essentially, default Syndication Links plugin comes with SVG hex colors on by default but then you can choose to uncheck a box to disable that so developer can write his own styling since SVG fill attributes could have `currentColor` by default.

**Comment by dshanske** [comment]
We can automate the creation of the php file to include. I already do that with Grunt for the colors and names

**Comment by dshanske** [comment]
I have released a version into development that uses inline svg.

**Comment by dshanske** [comment]
It was an automation issue. Fixed now.
