### ISSUE TITLE
Syndicate Response URL

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#102]
When a Post Kind is published with a Response URL and this published post content is syndicated to a silo, the Response URL is not included in the syndicated content.

I think there's a case to be made that the Response URL should be included in that syndicated content, as the last/only URL or 2nd to last URL to give the content more context where it goes.

**Comment by dshanske** [comment]
As the syndication uses parsed microformats, this is not specifically an issue with this plugin.
