### ISSUE TITLE
Feature request: "Syndicate to" service checked by default

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#105]
Depending on the post kind, always check one or more of the "Syndicate to" services. 

For example, any time I write a note, I go down to the "Syndicate to" widget and check the Twitter box. It would be useful to set this up so that choose a post kind of note means the Twitter service checkbox box is prepopulated.

**Comment by dshanske** [comment]
Related to #89

**Comment by dshanske** [comment]
Closed in favor of #89
