### ISSUE TITLE
A few display quirks

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#107]
With the most recent update I'm noticing a few small edge case quirks that seem to have popped up:

For syndication to indieweb.xyz the displayed result (set for icon only) is giving a relatively interesting "info" icon,which is a reasonable proxy, but sadly the hover text is also "info" instead of a more useful or expected "indieweb.xyz".

For syndications to reading.am (which I'm guessing still doesn't have a service specific icon) instead of giving the old default image of a globe icon, it's not displaying anything at all. I haven't tested specifically, but are unmapped urls still given that old default icon? 

I'm still seeing issues with my chrisaldrich.wordpress.com URL. Previously it displayed a blank space (presumably not able to understand the inpub), but the newer version is displaying the word "WordPress" even when I'm using icons only. (Example: https://boffosocko.com/2019/02/14/a-sketch-for-an-indieweb-bullet-journal/#Syndicated%20copies) My initial inclination is that the two instances of "WordPress" at https://github.com/dshanske/syndication-links/blob/057733d921b485cf8f0eb98b28b104ccb708bd21/includes/class-syn-meta.php#L333 are both CamelCase when all the other examples around/near that segment of code are all lower case.

(originally published at https://boffosocko.com/2019/02/16/a-few-display-quirks-in-the-syndication-links-plugin/)

**Comment by dshanske** [comment]
Believe this is resolved
