### ISSUE TITLE
Scheduled post + Bridgy doesn't work

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#109]
When I scheduled a recent post, I checked the Bridgy box to syndicate to Twitter and then scheduled the post to be published automatically in the future. Unfortunately, when the post published itself, there was no syndication post to Twitter along with it.

**Comment by dshanske** [comment]
Just pushed a new version. Can you test again?

**Comment by asuh** [comment]
With scheduled posts, would it make sense that when a post is scheduled and if a Syndicate To checkbox is checked, that checkbox stays checked after saving that post as a scheduled post? There's no visual indicator that says a scheduled post will also be syndicated because the Syndicate To item's checkbox was previously checked.

**Comment by asuh** [comment]
Success, either this was fixed or it looks like this could have been a cron job problem as well
