### ISSUE TITLE
Display issue on syndicated links

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#11]
I'm supposing it's a simple CSS display issue that's been baked in from the start, but I've noticed that when hovering over the individual output links indicating where a particular post has been syndicated to, the icon and the word (eg, the Facebook icon and the world "Facebook") shift over a few pixels, I'm supposing in part to indicate they're being hovered over. In general this isn't horrible, but there are some examples where it make the functionality difficult or nearly impossible to use and at best simply wonky.

As an example, try hovering over the Facebook link at http://lfl8424.boffosocko.com/2015/08/12/todays-books-august-12-2015/ and it shifts things enough that one block of text at the end of the line shifts to the next line.

Even worse, on that same page it becomes nearly impossible to click on the "adamshillca" synidcated link because it shifts incessantly from it's initial position to the following line. 

Perhaps it's my particular CSS, but, that I'm aware of, I haven't handcoded any of the relevant CSS, and have the same issue on two separate sites with different themes/CSS. I'm also supposing it's done purposefully as it occurs on https://david.shanske.com/ as well, though it's not as obvious there as you're just outputting the social media icons only.

**Comment by dshanske** [comment]
I'll see about removing the hover code. It might be left over.
