### ISSUE TITLE
Seem to need Post Kinds plugin to do syndicate-to Twitter via Bridgy

### ISSUE THREAD

**Issue by GidiKroon** [dshanske/syndication-links#126]
In my limited tests (I only have a live site which also publishes to the fediverse with the ActivityPub plugin so I can't keep making test posts) I didn't get syndicating to Twitter via Bridgy to work, even though I had the Sempress theme for its microformats2, Bridgy and Twitter set up so it successfully sends from the preview action, the Indieweb plugin, as well as the IndieAuth, Webmention and Micropub plugins. The checkbox appeared in the block editor and I selected it before clicking Publish, but nothing was ever sent to Bridgy and the syndication links field remained empty.

When I tried the classic editor it still didn't work but I finally had half success when I also installed Post Kinds. In this case the Bridgy url was entered to the syndication links and Bridgy was triggered via a webmention. (but then bridgy failed, probably a problem there. see [here](https://gidikroon.eu/2020/06/28/final-test-you-can-stop-ignoring-after-this-one/) and the [bridgy log](https://brid.gy/twitter/gidikroon) shows that it sees an empty syndication-links div).

Anyway, if Post Kinds is indeed a dependency, and it is not compatible with the block editor, can you please let the readme indicate that this plugin is also not compatible with the block editor? Thanks.

(The actual issue I'm having I consider not solvable until I'm able to do more tests)

(BTW If there is a plugin that contains only the syndication providers for Micropub and maybe a UI, which doesn't modify the content after publishing, I'd like to know about it)

**Comment by dshanske** [comment]
That is rather odd. Post Kinds shouldn't be required for this to work. Admittedly I'm using the Classic Editor. But it is supposed to schedule the syndication to fork into the background...so unless I picked a hook that isn't triggered in the Block Editor, it should work.

**Comment by GidiKroon** [comment]
Thank you for the response.
I've done another test, with the new version, and this time a webmention was sent (after some minutes) while using the block editor and without Post Kinds installed. So my earlier conclusion was wrong and I will be closing the issue. Something else must have been going on yesterday. Sorry for drawing the wrong conclusion.
