### ISSUE TITLE
Better UI for relme 

### ISSUE THREAD

**Issue by dshanske** [dshanske/syndication-links#13]
Using the relme features are not intuitive.

**Comment by gRegorLove** [comment]
From @tantek "Syndication Links issue: zero discoverability for how to enter social media profile links, once you have installed the plugin. The "description" does not tell you how to use Syndication Links to set up rel=me."

Discussion: http://indiewebcamp.com/irc/2015-12-03#t1449191152527

**Comment by chrisaldrich** [comment]
I'm also noticing in the affiliated Rel-me Widget that seems to be included here, it uses the font sets to include potential social media icons in a relatively nice way, but that in fact the `<a href>` tags generated within the widget don't actually include rel="me" along with them. Unless I'm missing something this would seem to defeat the purpose of having a Rel-me Widget.

I'm supposing that in the settings box for "List of Rel-Me Links for This Site" that one would simply put in the raw URL  like `http://www.twitter.com/username` which when output into the Rel-me widget would get wrapped like this: `</section><section id="relme_widget-2" class="widget relme_widget"><div id="relme_widget" class="relmewidget"><ul class="social-icon"><li><a rel="me" href="https://www.twitter.com/username" ></a></li></ul>`

One could then put the widget on the front page, every page, or even custom set it to appear only on the posts where a particular author (corresponding to that of the particular user) happens to be.

**Comment by dshanske** [comment]
Rel-Me will be removed in the next version of Syndication Links as it is being superseded by a new version in the Indieweb plugin. Therefore closing issue for now.
