### ISSUE TITLE
How to add new domain and its name?

### ISSUE THREAD

**Issue by jackysee** [dshanske/syndication-links#132]
I want to add a syndication link for https://matters.news , currently it would display 'Summary' for that.  I can modify the class-syn-link-domain-icon-map.php to add the domain so that it displays the text 'matters'. How can I add outside of the plugin?

**Comment by dshanske** [comment]
Summary is the name of the generic file for that. There is a filter to change the icon, but not the name. I should add one regardless. But would that help?

**Comment by jackysee** [comment]
I think that's good enough.

**Comment by dshanske** [comment]
4.3.1 adds new filters to allow this so you don't have to modify the file. Adding notes to the readme.
