### ISSUE TITLE
Disabling all providers shows all providers in New Post page

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#133]
After updating the plugin, I didn't realize the providers were all disabled.

![Screen Shot 2020-09-11 at 11 17 26](https://user-images.githubusercontent.com/454064/92959354-84a8b080-f420-11ea-92c0-2d870d46e536.png)

When I went to write a new post, I suddenly saw more providers available. 

![Screen Shot 2020-09-11 at 11 17 12](https://user-images.githubusercontent.com/454064/92959464-b7eb3f80-f420-11ea-972d-4defb5a03dac.png)

I didn't think much of it, but wanted to syndicate to Twitter like I previously had. When I published the post, it didn't syndicate to Twitter as I had assumed, but instead appeared to syndicate to bridgy's twitter url: https://brid.gy/publish/twitter

My suggestion is to remove "Enable Syndication to Other Sites" checkbox, and enable that functionality to each of the checkboxes themselves. If no providers are checked, nothing is enabled.

**Comment by dshanske** [comment]
The unchecking of the enable option actually causes the load to stop, so none of that code is executed.  Either way, fixed the issue with the disabling of all providers. As for the syndicate to bridgy's twitter URL, that is required. When Bridgy returns a Twitter URL, it will update to the actual Twitter URL.
