### ISSUE TITLE
"Enable the Following Providers” area is blank.

### ISSUE THREAD

**Issue by khurtwilliams** [dshanske/syndication-links#134]
In the Syndication Links admin page, the list of providers under the "Enable the Following Providers", is blank.

WordPress 5.5.1–en_GB
Syndication Links Version 4.2.5
IndieWeb Version 3.4.3

![Screenshot 2020-09-24 at 2 50 40 PM](https://user-images.githubusercontent.com/686971/94187032-6c4f8180-fe75-11ea-9133-2b2111026b49.JPEG)

![  ](https://user-images.githubusercontent.com/686971/94187325-c9e3ce00-fe75-11ea-82b1-d1efcebe2341.JPEG)

**Comment by dshanske** [comment]
@khurtwilliams This still going on?

**Comment by khurtwilliams** [comment]
Yes, but it only happens when I disable the Webmentions plugin.

**Comment by dshanske** [comment]
It would.. half of the plugins require Webmentions

**Comment by dshanske** [comment]
Closed and renamed Bridgy name to include Webmention.
