### ISSUE TITLE
Gutenberg error: "invalid stored value, and cannot be updated to null"

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#138]
WordPress 5.5.3
Syndication Links 4.3.0
Firefox 83

I edited a page and saved it a few times, went to do something else in another tab, came back to re-save and the following error appeared above the editor at the top left:
`Updating failed. The mf2_syndication property has an invalid stored value, and cannot be updated to null.`

<img width="666" alt="Screen Shot 2020-11-27 at 23 17 25" src="https://user-images.githubusercontent.com/454064/100496209-2e860800-3107-11eb-8522-69ad85735d34.png">

No errors in the error log that relates to this issue.

I realize this is probably a Gutenberg specific but maybe there's something we an try to fix this.

**Comment by dshanske** [comment]
This one should be fixed in the latest commit.
