### ISSUE TITLE
Brid.gy error: Couldn't find link to www.brid.gy/publish/twitter

### ISSUE THREAD

**Issue by sebastianweiss23** [dshanske/syndication-links#139]
Hi,

since around 2-3 weeks, my posts don't get published to twitter via brid.gy anymore. I found on the brid.gy website the error message "Couldn't find link to www.brid.gy/publish/twitter".

Here is one example: [https://brid.gy/log?start_time=1606673933&key=agdicmlkLWd5clALEg1QdWJsaXNoZWRQYWdlIilodHRwczovL3NlYmFzdGlhbndlaXNzLm1lLzIwMjAvMTEvMjkvMzYyLwwLEgdQdWJsaXNoGICA8MHDnoAKDA ](url)

To be honest, I don't know what the problem is, as I'm assuming the plugin normally takes care of this link. I also have a second test blog, where the publishing works smoothly. 

Any hints to solve this issue are appreciated. :)

**Comment by dshanske** [comment]
I'm planning on investigating this further as I experience intermittent issues with this

**Comment by sebastianweiss23** [comment]
> I'm planning on investigating this further as I experience intermittent issues with this

Thanks @dshanske :)

**Comment by bekopharm** [comment]
I did finally update to Syndication Links `4.3.9` and the POSSE is broken for me too.

When I click syndicate to XY an database entry is created in `postmeta` **without** `meta_value` :

> |  502930 |  477136 | _syndicate-to           |                                                                                                                                                                                                                                           |

That's read in `do_pings()` and deleted again but since it's empty it crashes later on in `syndication($post_ID, $syndicate_to)` because `$syndicate_to` is not an Array as expected:

```
Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in  wp-content/plugins/syndication-links/includes/class-post-syndication.php:152
[...]
#17 phar:///usr/local/bin/wp-cli.phar/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp-cli.phar(4): include('...')
#19 {main}
  thrown in wp-content/plugins/syndication-links/includes/class-post-syndication.php on line 152
```

If one would try to manually publish via brid.gy it will yield the error message `Couldn't find link to www.brid.gy/publish/twitter` because it's never added to the syndication links. The `_syndicate-to` option is deleted at this point and it won't try again.

No idea why it fails to add the syndication targets tho - POST looks good :shrug: - mebbe it's ditched in `sanitize_text_field( $_POST['syndicate-to'])`
![image](https://user-images.githubusercontent.com/5016428/150437798-186d75c9-cd18-4fc9-b971-d6ac6e5a0e9b.png)

**Comment by metbril** [comment]
> I did finally update to Syndication Links 4.3.9 and the POSSE is broken for me too.

What was the last known version that was working for you?

**Comment by dshanske** [comment]
Odd. Will look again

**Comment by metbril** [comment]
When I downgrade to 4.3.0 Twitter is working again. I'll upgrade step by step to see when it fails.

**Comment by metbril** [comment]
The upgrade from 4.3.6.to 4.3.7 breaks syndicate to twitter.

Comparing between tags:

https://github.com/dshanske/syndication-links/compare/4.3.6...4.3.7

I'm 99% sure it's related to this commit:

https://github.com/dshanske/syndication-links/commit/17bb264fd49b876796b7698c4f592d31e6f32b3c#diff-2abda1ed160b11688302303000d1922b69e2ffa61d03c257b7f0efce3254f85a

**Comment by dshanske** [comment]
Wouldn't surprise me. They made me do a lot of sanitization.

**Comment by metbril** [comment]
> They

Who's 'they'?

**Comment by dshanske** [comment]
> > They
> 
> Who's 'they'?

I received a warning from the WordPress plugin repository. I may have overdone the sanitization.

**Comment by dshanske** [comment]
Releasing 4.3.10 which changes the sanitize method, which should fix the problem. Also made some minor changes to how it handles the syndication which I hope works better. Close if addresses.

**Comment by dshanske** [comment]
I checked, and this seems to work for me.

**Comment by bekopharm** [comment]
> Releasing 4.3.10 which changes the sanitize method, which should fix the problem. Also made some minor changes to how it handles the syndication which I hope works better. Close if addresses.

https://github.com/dshanske/syndication-links/commit/06b9001aff652c239614d7391c790f59ea57ed4a#diff-2abda1ed160b11688302303000d1922b69e2ffa61d03c257b7f0efce3254f85aR353 fixes it :partying_face:
