### ISSUE TITLE
Hook for cache busting

### ISSUE THREAD

**Issue by jackysee** [dshanske/syndication-links#140]
I'm using WP Fastest Cache. When POSSE both to twitter and mastodon via brid.gy, the mastodon one (2nd one) would fail as the web is cached and the mastodon publish link is not found yet. Even the line `do_action( 'edit_post', $post_id, $post );
` can't seem to bust the cache. I found that it can be solved by adding a clear cache before POSSE.

```diff
diff --git a/includes/class-syndication-provider-webmention.php b/includes/class-syndication-provider-webmention.php
index a867330..c448a33 100644
--- a/includes/class-syndication-provider-webmention.php
+++ b/includes/class-syndication-provider-webmention.php
@@ -41,6 +41,10 @@ class Syndication_Provider_Webmention extends Syndication_Provider {
 		if ( ! $post_id ) {
 			$post_id = get_the_ID();
 		}
+   if(has_action("wpfc_clear_post_cache_by_id")){
+       do_action('wpfc_clear_post_cache_by_id', false, $post_id);
+   }
 		$post = get_post( $post_id );
 		add_syndication_link( $post_id, $this->get_target() );
 
```

But it's too plugin-specific. It would be nice to have a hook here so customization can be made.

**Comment by dshanske** [comment]
Happy to add the hook next update.

**Comment by dshanske** [comment]
Hook now added.
