### ISSUE TITLE
Hidden links on Front page/Archive/Search results are bad for seo

### ISSUE THREAD

**Issue by kuz-z-zma** [dshanske/syndication-links#149]
There is a setting that allows to enable display of syndication links on pages other than Single Post with a potentially dangerous behaviour:

> Show on Front Page, Archive Page, and Search Results – If checked the icons will show on pages other than a single view. **If not checked, the icons will be hidden by the links will remain**.

Mu concern is about the highlighted part - hidden text and especially hidden links (in any way) been considered a big "NO" by search engines since forever, are synonymous black hat seo and are promised retribution & bans from search results by all search engines.
So... why do it?

Ideally disabling this setting should not add them at all on listed pages, or offer this as an option.

**Comment by dshanske** [comment]
This is not a change in behavior of the plugin. It was more a clarification in the text. The purpose of the links is to be parsed by a microformats parser. The same links appear visibly on the single posts. In the interest of compromise, I should add a third choice, but I'd like to figure out a compromise that keeps useful data there.

**Comment by Ruxton** [comment]
@dshanske Yeah it shouldn't hide the links, as @kuz-z-zma points out hidden hrefs are an SEO no-no and are generally processed at a negative to your "score".  I always imagined this was "links on or off" and that's how it should work imo.

I'd argue from a structural sense, those links dont belong in the body.

**Comment by dshanske** [comment]
I'm adjusting it to a data tag.

**Comment by dshanske** [comment]
This was resolved in 4.3.9
