### ISSUE TITLE
Add social.coop to Mastodon server list

### ISSUE THREAD

**Issue by fncll** [dshanske/syndication-links#151]
The https://social.coop server isn't mapped in this plugin, resulting in a generic icon in the Syndication Links section of a post there

Discussion of this issue on the IndieWeb chat here: https://chat.indieweb.org/wordpress/2022-05-12#t1652396467827100

**Comment by dshanske** [comment]
Unable to accommodate every Mastodon server, but will see about a way you could add this to config in the admin.

**Comment by fncll** [comment]
I don't understand how the code works, but this seems like basically a duplicate of #99 and I can understand why you wouldn't want to have to keep adding server after server (though, tbf, social.coop is one of the bigger ones). Clearly this is not an issue of urgency. It's too bad there's no way to know from the simple fact that it is being syndicated to Mastodon as an option that the destination must be a mastodon server.

**Comment by dshanske** [comment]
In #99 I extracted it from where it was stored in another plugin's data.. want to do something similar rather than hard coding

**Comment by dshanske** [comment]
@fncll If the Mastodon URL is the one in your user profile, it should use it in the latest release. Tell me if it works and I can close this.

**Comment by dshanske** [comment]
Closing this due no response.
