### ISSUE TITLE
Help Wanted: Setting up POSSE

### ISSUE THREAD

**Issue by vishae** [dshanske/syndication-links#154]
I can't get POSSE to work via Syndication Links and I'm not sure why. 
I'm on a self-hosted version of WordPress.

My understanding of the steps are:
1. I go to the `/wp-admin/profile.php` section of my site and fill in my username (let's use Twitter and Mastodon for this example)
2. I go to [brid.gy](https://brid.gy) and log into/authorise both Twitter and Mastodon
3. Go to Syndication Links settings `/wp-admin/admin.php?page=syndication_links` and enable "Twitter via Bridgy" and "Mastodon via Bridgy"
4. When creating a new post, remember to tick either "Twitter via Bridgy" or "Mastodon via Bridgy" in the "Syndicate To" box
5. Click Publish

I had gotten Twitter working many years ago, but at some point it broke and I've never been able to get it back again.
I've managed to get "NextScripts: Social Networks Auto-Poster" working for Twitter and "Mastodon Autopost" for Mastodon, but I would prefer to use Syndication Links (not to mention Mastodon Autopost currently doesn't work with Syndication Link, in that the Syndication Links field doesn't auto-populate with the URL to the Mastodon post).

It would be great if someone can point me to where I went wrong.

**Comment by dshanske** [comment]
Fixed the Mastodon Autopost issue. The author changed where they were storing the URL.

New version will fix this, as well as a lot of other new options.

**Comment by dshanske** [comment]
Closed due changes in the plugin
