### ISSUE TITLE
Can't add second synd link

### ISSUE THREAD

**Issue by snarfed** [dshanske/syndication-links#169]
After creating a post with _Syndicate to Bridgy Fed_ checked, if I try to add a second synd link and update the post, it updates successfully, but the second synd link doesn't get stored. The post doesn't show it, and if I reload the editor for the post in admin, the second synd link isn't there.

Fwiw, I hit #168 while initially creating this post, so that may be contributing here.

**Comment by dshanske** [comment]
@snarfed I just tested this, and I can add/remove links. Not sure if related to the other problem, which would have affected retrieving the existing links for saving purposes.

**Comment by snarfed** [comment]
This was probably fixed by 4.4.2 fixing #168. Thank you!
