### ISSUE TITLE
Drop webmention vs micropub options

### ISSUE THREAD

**Issue by snarfed** [dshanske/syndication-links#174]
A recent version added webmention vs micropub options for each provider. I get that Micropub feels more reliable; that's great! But we probably want to revert this. We've already heard confused users ask what the difference is, which one they should use, whether one is for original posts and one is for replies, etc. Webmention and Micropub are plumbing, not user-meaningful features. If you like Micropub better, let's just switch to it and drop webmention!

**Comment by dshanske** [comment]
Tried to address this with a hidden flag.

**Comment by snarfed** [comment]
Awesome, thank you! Was this 79a74769bcb28d0f360ba1e8aa73d4daba67769e? I assume you'll add docs for that hidden flag eventually?

**Comment by dshanske** [comment]
Yes, was hoping to get feedback on how the posse code is working and what people want
