### ISSUE TITLE
Checkboxes on settings page would benefit from labels

### ISSUE THREAD

**Issue by janboddez** [dshanske/syndication-links#175]
I mean, each label + checkbox could be wrapped into a `label` element, which would improve accessibility (make the labels clickable). Like the radio buttons.

**Comment by ghost** [comment]
I agree that accessibility of the checkboxes could be improved somewhat. 
As a screen reader user, the experience of using the settings page is 
slightly frustrating without proper labeling. I will point out that the 
way things are currently when using NVDA on Windows, ChromeVox on Chrome 
OS and Orca on Linux are all the same and would benefit from proper 
labeling of the controls to make them more accessible for screen reader 
users like myself.


-- Gregory Lopez

**Comment by dshanske** [comment]
I think I found the setting to automatically add this. I thought I had added that.

**Comment by janboddez** [comment]
The issue is here: https://github.com/dshanske/syndication-links/blob/c44b04c89e9d1db0bc814845d10964ecb1b42ce2/includes/class-syn-config.php#L357

A fix would be:
```
<li>
	 <label><input name='<?php echo esc_attr( $args['name'] ); ?>[]' type='checkbox' value='<?php echo esc_attr( $post_type->name ); ?>' <?php checked( in_array( $post_type->name, $option ), true ); ?>/> 
	 <?php echo esc_html( $post_type->label ); ?></label>
</li> 
```
Rather than have the heading "link" to "the options," you'd have each label "link" to its respective option. I think, I'm not on my main computer so can't do a PR right now.

**Comment by dshanske** [comment]
I was focused on the other settings...I will add the markup for this one

**Comment by dshanske** [comment]
They have labels...

@janboddez @greg-lopez How am I doing on this one? I just did a whole label thing.

**Comment by ghost** [comment]
I'm assuming an update will be pushed soon... Still on v4.4.9 as of a few moments ago.

**Comment by dshanske** [comment]
@greg-lopez Yes, trying to figure out if this is still an issue, or what I should do, as the issue was back in February.

**Comment by dshanske** [comment]
Closed. Can reopen if more label feedback is provided.

**Comment by janboddez** [comment]
If you'd really rather not just wrap checkbox and label in `label` tags, the `for` attributes must match the `id`s (not `name`s). Several inputs don't have an ID, which is why it still doesn't work.

To test, just click all of the labels, see what happens. They should (un)check the corrsponding radio or checkbox inputs. Also, sometimes a `th` has a label in it that seems to correspond with a radio group but not with an actual item. Better remove those, I think (they don't do anything when clicked).
