### ISSUE TITLE
Critical error after updating to 4.4.5

### ISSUE THREAD

**Issue by stephenpieper** [dshanske/syndication-links#177]
WordPress version 6.1.1
Active theme: Autonomie (version 1.0.0)
Current plugin: Syndication Links (version 4.4.5)
PHP version 7.4.33

I just updated to the latest version and the following critical error resulted locking me out of the site:

Error Details
=============
An error of type E_ERROR was caused in line 9 of the file .../wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention-bridgy.php. Error message: Uncaught Error: Call to undefined method SynProvider_Webmention_Bridgy_Twitter::register_setting() in ...wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention-bridgy.php:9
Stack trace:
#0 ....wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention-bridgy-twitter.php(17): SynProvider_Webmention_Bridgy->__construct(Array)
#1 .../wp-content/plugins/syndication-links/syndication-links.php(70): SynProvider_Webmention_Bridgy_Twitter->__construct()
#2 ...wp-content/plugins/syndication-links/syndication-links.php(168): syndication_links_register_providers(Array, '/includes/webme...')
#3 ...wp-includes/class-wp-hook.php(308): syndication_links_init('')
#4 .../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 .../wp-includes/plugin.php(517): WP_Hook->do_action(Array)

**Comment by dshanske** [comment]
Will issue an update within the hour

**Comment by tmichellemoore** [comment]
@dshanske  I reinstalled so I could also provide try error. Its below.

Fatal error: Uncaught Error: Call to undefined method SynProvider_Webmention_Bridgy_Twitter::register_setting() in /home/michmgfh/tmichellemoore.com/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention-bridgy.php:9 Stack trace: #0 /home/michmgfh/tmichellemoore.com/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention-bridgy-twitter.php(17): SynProvider_Webmention_Bridgy->__construct() #1 /home/michmgfh/tmichellemoore.com/wp-content/plugins/syndication-links/syndication-links.php(70): SynProvider_Webmention_Bridgy_Twitter->__construct() #2 /home/michmgfh/tmichellemoore.com/wp-content/plugins/syndication-links/syndication-links.php(168): syndication_links_register_providers() #3 /home/michmgfh/tmichellemoore.com/wp-includes/class-wp-hook.php(308): syndication_links_init() #4 /home/michmgfh/tmichellemoore.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #5 /home/michmgfh/tmichellemoore.com/wp-includes/plugin.php(517): WP_Hook->do_action() #6 /home/michmgfh/tmichellemoore.com/wp-settings.php(480): do_action() #7 /home/michmgfh/tmichellemoore.com/wp-config.php(109): require_once('/home/michmgfh/...') #8 /home/michmgfh/tmichellemoore.com/wp-load.php(50): require_once('/home/michmgfh/...') #9 /home/michmgfh/tmichellemoore.com/wp-blog-header.php(13): require_once('/home/michmgfh/...') #10 /home/michmgfh/tmichellemoore.com/index.php(17): require('/home/michmgfh/...') #11 {main} thrown in /home/michmgfh/tmichellemoore.com/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention-bridgy.php on line 9

Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/michmgfh/tmichellemoore.com/wp-includes/functions.php on line 5835

Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/michmgfh/tmichellemoore.com/wp-includes/functions.php on line 5835
There has been a critical error on this website.

**Comment by dshanske** [comment]
Issued emergency update 4.4.6, can you try? This should all be addressed.

**Comment by stephenpieper** [comment]
Fixed, thanks.

**Comment by tmichellemoore** [comment]
Fixed. Thank you!
