### ISSUE TITLE
Not seeing the syndication link field

### ISSUE THREAD

**Issue by troutcolor** [dshanske/syndication-links#179]
Hi,
I updated to Syndication Links  4.4.6  and I no longer see the syndication links metabox on posts. It is not available in Screen Options either. 
I checked a couple of older post that that syndicated links filled in. They do show the icons and links on the post, but no fields in the editor.
I do see a metabox 'Syndicate Logs' which I'd not notice before?

I quite often add links manually after cross posting via micro.blog or natively to twitter & mastodon.

WordPress 6.1.1  https://johnjohnston.info/blog/

cheers

John

**Comment by dshanske** [comment]
Classic or Block editor? And did you enable for specific post types in the config?

**Comment by troutcolor** [comment]
> Classic or Block editor? And did you enable for specific post types in the config?

thanks

Classic, although I have blocks enabled, **edit** by that I mean I use the classic plugin, but have the option to switch to blocks on a post. 
Post & Pages enabled. I presume from previous versions, I’ve been running the plug-in for years. 

cheers

John

**Comment by carol55512** [comment]
For what it's worth, I've got the same issue. Classic Editor (though I did switch briefly to Block editor to see if it made a difference.)  Enabled for Posts and Pages, though I did uncheck and recheck the settings just to see if it made a difference. On Wordpress 6.1.1.

**Comment by dshanske** [comment]
Trying to figure this out. I just did exactly what you did, and I still see the Syndication Link box on two different sites.

The syndication log was added a few versions ago.

**Comment by troutcolor** [comment]
@dshanske Thanks,
This is what I see. 

<img width="439" alt="post-types-to-syndicate" src="https://user-images.githubusercontent.com/2952893/218979405-fc1c47ab-6f5a-4ea0-a19f-a2685a9168fa.png">

<img width="985" alt="screen-options" src="https://user-images.githubusercontent.com/2952893/218979411-0256e5d7-0d3b-4397-bb24-0fc605937307.png">

Happy to try any suggestions. I presume I could reinstall the plugin with out losing old syndication links?

cheers

John

**Comment by dshanske** [comment]
If I try changing something, would you test by installing a development version of the plugin?

**Comment by troutcolor** [comment]
> If I try changing something, would you test by installing a development version of the plugin?

Certainly. That would be great. 

Cheers

John

**Comment by dshanske** [comment]
@troutcolor If you could download the version in this repo and try it...I made post enabled by default, and the options only reflect other post types. Can you check post and something else if enabled?

**Comment by troutcolor** [comment]
@dshanske Thanks very much, that has sorted thing out. I can see the metabox and fill in fields as expected. 

Cheers

john
