### ISSUE TITLE
Saving draft shouldn't trigger syndication

### ISSUE THREAD

**Issue by snarfed** [dshanske/syndication-links#185]
Surprisingly, when you click the _Save draft_ link at the top of the WordPress editor, this plugin triggers syndication to all of the enabled providers. That should only happen when you publish or update a post, not when you save it as a draft.

**Comment by dshanske** [comment]
It shouldn't. I'm positive I stopped that. I'm going to have to study this.

**Comment by snarfed** [comment]
OK! Low priority, I'd vote for others like https://github.com/indieweb/wordpress-micropub/issues/283 before this.

If it helps, I'm on WP 6.2.2, SL plugin 4.4.11. (And WM plugin 4.0.9 and Semantic Linkbacks 3.12.0, but I assume those don't matter here.)

**Comment by snarfed** [comment]
Also, in case it helps, I don't think I see this happen when it auto-saves drafts, only when I manually click on the _Save draft_ link.

**Comment by dshanske** [comment]
When you save the post, it adds a key to the post, similar to the pingback functionality. when it runs that...it actually filters for publish. 

 $syndicate = get_posts(
                        array(
                                'meta_key'    => '_syndicate-to',
                                 'fields'      => 'ids',
                                 'nopaging'    => true,
                                 'post_status' => 'publish',
                         )
                 );


But if you disable the scheduling, it publishes immediately...except it does that without regard for the post_status.  Should be fixed now.

**Comment by snarfed** [comment]
woo thank you!
