### ISSUE TITLE
Add icon for Nostr

### ISSUE THREAD

**Issue by snarfed** [dshanske/syndication-links#194]
I've started using [Nostr](https://nostr.how/en/what-is-nostr) a bit, it'd be nice to have a dedicated icon for Nostr links! It has a bunch of different clients on different domains, here's an incomplete list:
* astral.ninja
* nos.social
* iris.to
* snort.social
* app.coracle.social
* primal.net
* habla.news
* nostr.band

Here are a couple possible icons:

<img src="https://github.com/snarfed/granary/blob/main/static/nostr_logo.png?raw=true">

<img src="https://github.com/snarfed/granary/blob/main/static/nostr_ostrich_logo.png?raw=true">

**Comment by dshanske** [comment]
https://github.com/mbarulli/nostr-logo - Seems someone came up with an SVG version.

**Comment by dshanske** [comment]
Resolved via [be1c4c6](https://github.com/dshanske/syndication-links/commit/be1c4c64b292a02977ce60e2c83ad4808ca205ce)
