### ISSUE TITLE
Best way to support this plugin from other WordPress plugins?

### ISSUE THREAD

**Issue by meitar** [dshanske/syndication-links#2]
Hi,

I maintain the [Tumblr Crosspostr](https://wordpress.org/plugins/tumblr-crosspostr), [Diasposter](https://wordpress.org/plugins/diasposter/), and [WP-Crosspost](https://wordpress.org/plugins/wp-crosspost) POSSE plugins and I'm just beginning to explore adding [`rel-syndication`](http://indiewebcamp.com/rel-syndication) support to these plugins by default. Each of these plugins stores the necessary information to construct a link to the syndicated copy of a post, so that part seems simple.

My question for you is whether you think it would make more sense to implement compatibility with your plugin through its filter hook called by my own plugins, or to supply you with a patch that would add support for my plugins to your plugin. I'm leaning towards the first approach just because it seems simpler, but I'm asking because it seems like there isn't really a standard solution for rel-syndication on WordPress yet, and you seem more tuned into where such development is going than I am.

Thank for your feedback. :)

**Comment by meitar** [comment]
After looking at your code, I realized that my desired approach was not going to work unless I refactored some of your code. Please consider #3 for this reason.

**Comment by dshanske** [comment]
Closing this as fixed.
