### ISSUE TITLE
Add Bookwyrm's logo & sites

### ISSUE THREAD

**Issue by Guanchishan** [dshanske/syndication-links#208]
I hope to add the logo and related websites of Bookwyrm to this project. Bookwyrm is an open-source, decentralized, community-driven platform.

<s>In this PR #206 , I have added the logo of Bookwyrm and some of its main website links. I believe this will help our users to use Bookwyrm better.</s> I have created a new PR https://github.com/dshanske/syndication-links/pull/210, which only adds the Bookwyrm logo and one official Bookwyrm instance.

I look forward to everyone’s feedback and am willing to make any necessary modifications to meet the project’s needs.

**Comment by dshanske** [comment]
@Guanchishan Commented on your PR. Sorry for the delay on this, it's been a busy few months. Catching up now.

**Comment by Guanchishan** [comment]
> @Guanchishan Commented on your PR. Sorry for the delay on this, it's been a busy few months. Catching up now.

Thank you for your checking!

**Comment by Guanchishan** [comment]
I have created a new PR #210, which only adds the Bookwyrm logo and one official Bookwyrm instance.

**Comment by dshanske** [comment]
This was committed previously
