### ISSUE TITLE
Duplicated syndication links when using with SNAP

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#21]
Today, I started experimenting using SNAP as part of my POSSE regimen and noticed the following quirk with syndication-links installed:

![snap duplication](https://cloud.githubusercontent.com/assets/5882943/13942624/b7061eaa-efb1-11e5-9ee9-837ee4f46c59.PNG)

SNAP seems to be adding the top line saying "Also on" along with the three written text social networks Facebook, Tumblr, and Twitter (verified by disabling SNAP), while syndication-links plugin adds the bottom line saying "Syndicated to:" followed by the much prettier social media icons. (For comparison, the Google+ and LinkedIn icons are as a result of manually placing the URLs into syndication-links's box on the post's editor.)

Naturally, I'd much prefer (and I'm sure most others would as well) syndication-links's method of output given that it's more flexible and customizable. The question is how can one hide/disable the output from SNAP, but while still keeping the additional URL data they're backporting from POSSE for display into syndication-links?

Is it worth adding a configuration toggle in the settings to disable the SNAP output version for future cases/conflicts like this?

**Comment by dshanske** [comment]
I don't think it is Syndication Links. The Also on looks like jihaisse's old rel-syndication plugin. I used the code to extract SNAP and Social data from it.

**Comment by chrisaldrich** [comment]
Good catch @dshanske! It was exactly https://github.com/jihaisse/wordpress-syndication that was the cause. I could have sworn that I'd cleaned out all of the older/legacy indieweb plugins after the "master" IndieWeb plugin was rolled out a while back, but apparently that one was quietly hiding in my plugins folder waiting to catch me.
