### ISSUE TITLE
New icons: read.cv and posts.cv

### ISSUE THREAD

**Issue by nsmsn** [dshanske/syndication-links#215]
If I wanted to contribute a new icon or website, should I submit a PR with a SVG file or should I contribute to the Simple Icons project?

**Comment by nsmsn** [comment]
1. https://read.cv is a professional social network silo, similar to LinkedIn, founded by Andy Chung in 2021.
![readcv](https://github.com/user-attachments/assets/7ff9ece9-c27a-4fa0-a2cb-4e116c51b34b)

2. There is also a microblogging companion app for read.cv, at https://posts.cv
![posts](https://github.com/user-attachments/assets/96aa229f-3c16-4bd8-947e-a4a5eaf76e30)

Attaching official SVG logos for both. Official brand color for each service is #000000

**Comment by nsmsn** [comment]
Hmmm, looks like there already is a read.cv icon in Simple Icons: https://simpleicons.org/?q=read.cv

**Comment by dshanske** [comment]
Then this should work without any issue? Reopen if needed.

**Comment by nsmsn** [comment]
Hmm, I'm not sure if this latest update worked on my site...the previous generic 'website' icon isn't showing for either my mastodon instance or posts.cv:

![Screenshot 2024-12-09 at 11 34 56 AM](https://github.com/user-attachments/assets/32ee4abe-9717-4717-83d5-5c1224619a33)


I tried updating this post, but its not working as I expected. https://nicksimson.com/notes/3dcb441228/
