### ISSUE TITLE
UI enhancement: Don't display syndication text if nothing is syndicated

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#22]
If there are no copies syndicated, the "syndicated to" (or other optional text) shouldn't display.

![empty syndicated to](https://cloud.githubusercontent.com/assets/5882943/15279988/910446c4-1adf-11e6-8196-6ab6715c8037.PNG)

**Comment by dshanske** [comment]
It shouldn't be doing this at all, to be honest. The code is there. But I rewrote the area.
