### ISSUE TITLE
Call to undefined function extract_domain_name()

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#24]
After updating IndieWeb plugin and Syndication Links I get the following:

Fatal error: Call to undefined function extract_domain_name() in /wp-content/plugins/syndication-links/includes/class-syn-meta.php on line 52

This shows up in the page display where the content is usually otherwise output, so I still get the featured image, but no content and the error appears instead.

If I check the box for "Disable Syndication Links in the Content" the error disappears, but of course then the links don't show up on the page.

**Comment by dshanske** [comment]
Fixed. New version deployed
