### ISSUE TITLE
Display Text toggle not working

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#25]
I've updated to the most recent and everything works properly (I've toggled through most, but not necessarily all of the various combinations).

The one that doesn't seem to be working is the "Display Text", which as I recall swapped between the icons only view and the actual text (eg. "Facebook"). It doesn't seem to matter whether the "Display Text" is checked or not, it only displays the icons.

**Comment by dshanske** [comment]
I know I deprecated the alternate fontset because of the switch to SVG. Might bring back another option if I find a well maintained SVG set. But I tested the text and it was working. Will look into it.
