### ISSUE TITLE
Missing a closing </a> tag

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#26]
After the most recent update to the indieweb suite, I've noticed there doesn't seem to be a closing &lt;a> tag after the last syndication link which can cause spurious links to appear thereafter. Example: see http://boffosocko.com/2016/06/05/55673405/ which has an oddly linked gravatar author section.

![closing tag](https://cloud.githubusercontent.com/assets/5882943/16017746/19760b3c-3156-11e6-8a8a-3a2aab22b027.PNG)

Separately, The new svg icons are nice. I'm glad to see that Medium is included (that terrible silo). I'm sure you're aware you're missing WordPress and Tumblr icons (or they're not processing properly as *.tumblr.com or *.wordpress.com formats)...

**Comment by dshanske** [comment]
They should be. They are in the font set. Will check all.
