### ISSUE TITLE
Syndicated copies to silos include "Syndicated to:" text

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#32]
Similar to this issue with Jetpack: https://github.com/Automattic/jetpack/issues/4399

The text output from Syndication Links (the default text "Syndicated to:" ) shows up in the syndicated copies (and I'd generally think that most wouldn't want it from a UI/UX perspective). I've tried syndicating to most of the major platforms and Facebook and Tumblr appear to be the primary offenders.

Example:
Original: http://boffosocko.com/2016/07/16/the-indieweb-ified-library/
Syndicated Tumblr Copy: http://chrisaldrich.tumblr.com/post/147515812392/the-indieweb-ified-library
Syndicated FB Copy: https://www.facebook.com/ChrisAldrich/posts/10101055831666725?pnref=story

Perhaps the checks and the patch mentioned in https://github.com/Automattic/jetpack/issues/4399 could provide a solution?

**Comment by dshanske** [comment]
I did add them and removed the syndication links from RSS for now.

**Comment by dshanske** [comment]
How are we doing with this?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/32#issuecomment-275871556" class="u-in-reply-to"></a>I haven't seen anything like this pop up on any silos recently. Seems to be working as expected.

**Comment by dshanske** [comment]
Thinking of adding a filter to my work on Syndication, "the_content_syndication" which will match the behavior of "the_content" and "the_content_rss". Then will update other plugins to not add their information to the content if it is being published for syndication. Have to figure out how to check for that though.

**Comment by dshanske** [comment]
I am going to close this for now as there is a setting.
