### ISSUE TITLE
Syndication to Medium

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#33]
Now that Medium's API now supports posting and in addition to their "import post" functionality (POSSE), their [bulk POSSE method](https://help.medium.com/hc/en-us/articles/218572107-How-to-move-to-Medium), as well as their [WordPress Plugin](https://wordpress.org/plugins/medium/), it would be great if Syndication Links could programatically grab the URL from the plugin for inclusion. (I don't think any of the other methods provide data, but I could be wrong.)

For reference the WordPress Medium Plugin is storing the data in postmeta in meta_key named "medium_post"

Here's an example from something that I posted recently from that field: 
`O:11:"Medium_Post":11:{s:16:"author_image_url";s:69:"https://cdn-images-1.medium.com/fit/c/200/200/0*ici7OvT6gSngj2t9.jpeg (14KB) ";s:10:"author_url";s:32:"https://medium.com/@chrisaldrich";s:11:"byline_name";N;s:12:"byline_email";N;s:10:"cross_link";s:2:"no";s:2:"id";s:12:"4335e2d72369";s:21:"follower_notification";s:3:"yes";s:7:"license";s:19:"all-rights-reserved";s:14:"publication_id";s:12:"12b80d28f892";s:6:"status";s:6:"public";s:3:"url";s:73:"https://medium.com/@chrisaldrich/wordcamp-orange-county-2016-4335e2d72369";}`

It's obviously the final URL in the array that you'd want to scrape.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/33#event-849178255" class="u-in-reply-to"></a>Thanks David! It was great to see you at IWC-LA. Thanks for flying out to see us all.

I'm confirming that I've updated and done a test syndication to Medium. This works perfectly.

**Comment by dshanske** [comment]
Glad to hear it.
