### ISSUE TITLE
UI/UX: Don't display "Text Before Links" text when empty

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#37]
With the plugin set up and "Text before links" set (to something like "Syndicated to:") that text displays even when there are no syndicated copies in the field. If there aren't syndicated copies, then ideally the text shouldn't appear. 

I thought this had been previously filed, but don't see it in the queue anymore, so apologies if it's a duplicate, or fixed in current code, but not in stable.

**Comment by dshanske** [comment]
I think this should work per specification now.
