### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#38]
I noticed that there doesn't seem to be an icon (or it's blank) within syndication links for SoundCloud. It doesn't display the default "share" icon, but shows up as a blank white spot. Maybe a typo in 'syndication-links/includes/class-syn-meta.php' as <code>'soundcloud.com'  => 'cloud',</code>instead of 'soundcloud'?

Additionally, Ghost and Mailto are explicitly supported in the code, but use the default share icon rather than native icons (perhaps because Ghost doesn't have none?)

Cross reference photo at http://boffosocko.com/2017/01/06/a-secondary-meaning-for-posse/

**Comment by dshanske** [comment]
The icons I am including do not include Soundcloud. Can you find me an SVG icon and the color for it?

**Comment by chrisaldrich** [comment]
The standard Soundcloud color is #f50;

A few locations for SVG versions (most with reasonable/open licenses):
https://codepen.io/ruandre/pen/howFi
https://www.iconfinder.com/icons/1298765/soundcloud_icon#size=128
http://iconmonstr.com/soundcloud/

**Comment by dshanske** [comment]
I added te icon. But the other links, can you advise what the actual links were?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/38#issuecomment-274690867" class="u-in-reply-to"></a>Apologies, it looks like I'd miscounted on the ghost.org link, which does in fact exist and render properly. It was the plus.google.com URLs which aren't being cut down properly and displaying the G+ icon the way they should and instead appear as a generic share icon.

The other is for syndicating via email (which I imagine isn't done often?) and appears on line 205 of 
https://github.com/dshanske/syndication-links/blob/52160d913fcf6d41406f468ee13323bc90a983b5/includes/class-syn-meta.php as 				`'mailto:'         => 'mail',`
Unless I'm formatting it painfully wrong, mailto:XXX links show up with the generic share icon instead of a mail icon.
