### ISSUE TITLE
Text Only and Hidden don't seem to work in 0e60a65

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#42]
Using the current Github version https://github.com/dshanske/syndication-links/commit/0e60a652a040598c551be20ed058a40215b84eff
in conjunction with WP 4.7.2
Perhaps you're aware, but just in case...

Selecting the display option "text only" displays both text and icons instead of just text.
Similarly selecting "hidden" still displays the text and icons instead of hiding them.

I don't think I'd use "hidden" myself, but adding it for those who don't want to display, but still want original post discovery for stuff like Bridgy is brilliant. GWG++

At some point I think for better UI, you had increased the priority of the plugin so that syndication links displayed above JetPack's "Share This" and "Like This" functionalities. Perhaps it changed as it's now displaying between the two again.

I like the decision to move the checkbox out for removing from the_content for theme support. Fewer people will likely be confused, particularly with the new option for hidden links, and anyone doing theme-specific support should understand the filter.

**Comment by dshanske** [comment]
Try it now.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/42#issuecomment-276285462" class="u-in-reply-to"></a>Hmmm... new bug somewhere...  Did it work for you?

Using deb83df with WP4.7.2: 

Regardless of the settings, nothing shows up, but when viewing the source of the page, I'm seeing the following for most, if not all, combinations:

`<ul class="relsyn"><li><a aria-label="Facebook" class="syn-link u-syndication" href="https://www.facebook.com/test" rel="syndication"> </a></li><li><a aria-label="Twitter" class="syn-link u-syndication" href="https://www.twitter.com/test" rel="syndication"> </a></li></ul>`

**Comment by dshanske** [comment]
I really have to stop working on things too late. Forgot to commit the new CSS. Will update soon

**Comment by dshanske** [comment]
Try again? It seems to work for me.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/42" class="u-in-reply-to"></a>Syndication links still display between JetPack's "Share This" and "Like This" functionalities, but everything else seems to be as expected now.

Good work!
