### ISSUE TITLE
Duplication of links upon update

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#45]
With v3.1.1 and relying on SNAP for POSSE, I'm noticing that after publishing and syndicating, if one comes back and edits a post and then updates it, Syndication Links regrabs the URL's and duplicates the links.

The first unedited version that is shown seems to be a plain http link and after editing/updating, the second duplicated link that is added automatically is an https version.  

Manually deleting either of the included links from the Syndication Links box doesn't get rid of the links.

This duplication of the links only happens on posts which have been later edited/updated.

example: http://boffosocko.com/2017/02/16/podcast-directories-why-cant-we/
Here the Twitter and Facebook links, which are generated from SNAP, are duplicated, first as http and then again as https. As a test, the two other syndication links are non-SNAP generated links: huffduffer was manually inserted, and the WordPress one was generated from the WordPress Cross Post plugin, so I'm guessing it's an issue caused by the storage of SNAP links (which are https) versus Syndications Links' storage.

**Comment by dshanske** [comment]
Interesting. I made changes in this area. I think I know what I can do to address.

**Comment by dshanske** [comment]
@chrisaldrich Can I close this?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/45#issuecomment-280858961" class="u-in-reply-to"></a>Ha! I thought you'd closed it ages ago! I haven't seen the issue in months...
