### ISSUE TITLE
Text Before Links text should have stylable class

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#47]
In tweaking/changing the CSS for the multiple sizes (around v3.1.1), you removed the class from the "Text Before Links" portion, so it's not easily accessible for theming.

It might also be worth putting the entire output into a div with a class as well for better CSS control.

cross reference: https://github.com/dshanske/syndication-links/issues/29

**Comment by dshanske** [comment]
Addressed in dev.
