### ISSUE TITLE
Move H-Card Widget to IndieWeb Plugin

### ISSUE THREAD

**Issue by miklb** [dshanske/syndication-links#52]
I'm not clear on the backstory or decision process of having both an rel=me widget and an h-card widget, but seems the h-card widget would be best in the core IndieWeb plugin. Based on comment in IRC, sounds like that was the plan.

Would a pull request help facilitate that?

**Comment by dshanske** [comment]
As mentioned in chat, the one built in is just not good enough to be moved. I want to retire it from this plugin

**Comment by dshanske** [comment]
Done. Will push to stable when the new one is in the Indieweb plugin.
