### ISSUE TITLE
Syndication removed from RSS feeds?

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#53]
I could have sworn at one point your removed syndication links from displaying in RSS feeds. 

Did they sneak back in?

![syndication in rss](https://cloud.githubusercontent.com/assets/5882943/25646148/48ebb25a-2f6a-11e7-885e-8fb2d9bc385d.PNG)

**Comment by snarfed** [comment]
looks like yes. they're hard coded to be included, as text, without a UI option to remove them. definitely not desirable. @dshanske mind either removing them from feeds, or apply the same rendering option (icons, text, both, hidden) that's currently chosen for HTML?

https://github.com/dshanske/syndication-links/blob/7e2b6fc8d2789774818c54c10631efd97b2fb590/includes/class-syn-config.php#L304-L309

thanks in advance!

**Comment by snarfed** [comment]
related: https://github.com/dshanske/syndication-links/issues/32#issuecomment-275871556

**Comment by dshanske** [comment]
I will see about adjusting the code again.

**Comment by dshanske** [comment]
There is now a setting for disabling them in feeds.

**Comment by snarfed** [comment]
woo thank you!

they actually never show up in the feed on my site now, regardless of whether that checkbox is checked or not. just fyi.
