### ISSUE TITLE
Simpleicons branch fatal error

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#64]
Alas, before even being able to test much of anything, I've run into a problem just on activation:

Fatal error: Uncaught Error: Call to undefined function simpleicons_syn_get_names() in /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php:216 Stack trace: #0 /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php(362): Syn_Meta::url_to_name('https://chrisal...') #1 /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php(406): Syn_Meta::get_syndication_links_elements(NULL, Array) #2 /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php(450): Syn_Meta::get_syndication_links(NULL, Array, Array) #3 /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php(439): get_syndication_links(NULL, Array) #4 /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php(454): Syn_Meta::get_post_syndication_links(NULL, Array) #5 /homepag in /homepages/32/d491429024/htdocs/boffoblog/wp-content/plugins/syndication-links/includes/class-syn-meta.php on line 216

**Comment by dshanske** [comment]
Sorry. Committed missing file for you to test.
