### ISSUE TITLE
Support for Keyring Social Importers

### ISSUE THREAD

**Issue by xavierroy** [dshanske/syndication-links#65]
Any chances of support for Keyring Social Importers (https://github.com/beaulebens/keyring-social-importers)?

I currently use this to import Instagram and Swarm data. I know I could use OwnyourGram or OwnyourSwarm. But I'm having trouble with Micropub in my site.

**Comment by dshanske** [comment]
It looks like he documents clearly where he stores the permalink, so it should be trivial to add support where documented. I will see what I can do.

**Comment by dshanske** [comment]
@xavierroy Try the febfixes branch and tell me if it works for you?

**Comment by beaulebens** [comment]
Hi, I'm the author of Keyring and the Social Importer plugins -- please let me know if it'd make sense for me to make any modifications/additions to either plugin as part of this support. I hadn't heard of syndication links until recently, but happy to support the effort.

**Comment by dshanske** [comment]
I just read through your importers, looked for the keys, and started checking them, but if you want, there is a filter for this to be done on the other side

**Comment by dshanske** [comment]
@beaulebens Anything I can do for you as well. I am a fan of your work, although not a current users.
