### ISSUE TITLE
Simpleicons branch issues

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#66]
The following services are missing and/or missing icons:
anchor.fm
app.net  (though it may be gone, people may have syndicated links there)
diigo.com
dreamwidth.org
huffduffer.com
news.indieweb.org (though I'm not sure what icon it would have?)
path.com
polldaddy
twitch.tv
whatsapp.com
ok.ru
Scoop.it
Sett.com
upcoming.org
vBulletin.com
VK.com.com
Weibo.com
username.withknown.com
Yo.com

Odd outliers:
* flipboard.com - works, but it's commonly used shortened version (used by SNAP) http://flip.it/ isn't covered - displaying from SNAP requires manual cut/paste as syndication links doesn't look for/import it from SNAP
* lanyard.com - works, but in the code it was listed simply as Lanyard (without the .com) typo??
* mastodon.social isn't covered, but to properly cover mastodon, you'd need to cover a bunch of separate instances, though most at least have the word "mastodon" and or "social" within their URL somewhere. Some sources of instances include: https://instances.social/list#lang=&allowed=&prohibited=&users= and https://joinmastodon.org/ 
* ebay's icon is alright, but seems small and unreadable by comparison with others

Misc:
For generic websites that aren't included, when output as "icon+text" it would be nice if they displayed the raw base URL without the TLD (.com, .org, etc.) as the text the same way the others do.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/66" class="u-in-reply-to"></a>Everything else seems to work rather well. I like the general look of the new set!

**Comment by dshanske** [comment]
Thanks. I will implement the changes I can based on this, and push a new version out.

**Comment by dshanske** [comment]
Do you have any of these icons? I'm using simpleicons.org, which is CC0. So you could submit a PR to add it to their set if you can follow their guidelines. I have a script to auto-update before a release.
