### ISSUE TITLE
Add icon for Untappd

### ISSUE THREAD

**Issue by khurtwilliams** [dshanske/syndication-links#69]
I have found a way to use Zapier to [push Untappd check-ins](https://islandinthenet.com/manual-until-it-hurts/) information from Untappd to my WordPress website.

I am requesting to add the icon for it to the Syndication Links Plugin. I have [examples](hhttps://islandinthenet.com/tag/untappd/) of it working.

**Comment by dshanske** [comment]
Sent upstream to my icon set, if they don't add, I will see about doing it manually.

**Comment by khurtwilliams** [comment]
Thank you.
