### ISSUE TITLE
Error Activating Plugin

### ISSUE THREAD

**Issue by RossGoodman** [dshanske/syndication-links#7]
When activating this plugin I get the following error:

Fatal error: Cannot redeclare store_bridgy_publish_link() (previously declared in /var/sites/r/rossgoodman.com/public_html/wp-content/plugins/wordpress-syndication-master/rel-syndication.php:192) in /var/sites/r/rossgoodman.com/public_html/wp-content/plugins/syndication-links/bridgy.php on line 7

**Comment by dshanske** [comment]
Already aware of this one. I've been merging the WordPress syndication functions into my plugin as the developer of that one is not active any longer. I've renamed the function either way and will be pushing a new version with that this weekend along with a bunch of other features.

The development version here on Github already has the name change.

https://github.com/dshanske/syndication-links/blob/master/bridgy.php#L7

**Comment by RossGoodman** [comment]
Thanks for that.

On 5 March 2015 at 16:33, David Shanske <notifications@github.com> wrote:

> Closed #7 <https://github.com/dshanske/syndication-links/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dshanske/syndication-links/issues/7#event-246888075>.
>



-- 
Ross
