### ISSUE TITLE
WordPress.com subdomain icons not showing

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#70]
In v3.3.0 subdomains of wordpress aren't displaying icons--perhaps because the system isn't properly able to view the subdomains like http://username.wordpress.com

It's giving a blank icon or empty space instead of even the default "world" icon.

Example: http://boffosocko.com/2017/12/15/threaded-replies-with-webmentions-in-wordpress/#Syndicated+copies+to

**Comment by dshanske** [comment]
Can you test this with the current version?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/70#issuecomment-368333933" class="u-in-reply-to"></a>Using the febfixes branch, installing, activating, and flushing caches. Somehow it doesn't seem to have fixed the issue. I also tried some of the others you've just added including: 
http://www.gumroad.com/1234test
http://aurelia.io/1234test
https://picarto.tv/1234test
https://unsplash.com/1234test

None of them showed icons at all either. Just blank spaces. Perhaps it's not finding the correct image to display? I don't see any conflicts within CSS. Not sure where/what else to check.

**Comment by dshanske** [comment]
Resolving this in the latest release... tested.
