### ISSUE TITLE
Settings link does not show up when indieweb plugin not active

### ISSUE THREAD

**Issue by jernst** [dshanske/syndication-links#74]
The documentation at https://wordpress.org/plugins/syndication-links/ says:

``
Settings for the Syndication Links plugin can be found in the main WordPress “Settings” tab in the admin dashboard
``

but they do not show up for me. They do show up under IndieWeb once that plugin is active. So either change the code or the documentation so they become consistent

**Comment by dshanske** [comment]
Cannot reproduce this.

**Comment by prtksxna** [comment]
Currently, the documentation says:

> Settings for the Syndication Links plugin can be found in the main 
> WordPress “Settings” tab in the admin dashboard, or if the Indieweb 
> plugin is installed, under the Indieweb tab.

I think this issue can be closed.
