### ISSUE TITLE
Feature Idea: UI code to create an original-of page and/or widget

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#78]
I noticed that Kartik has an an original-of page at <https://kartikprabhu.com/original-of> which may have inspired the [original-of URL functionality for use in Syndication Links](https://github.com/dshanske/syndication-links#how-can-i-look-up-the-original-if-i-have-a-syndication-link).

For improved UI, is there a code snippet that could be created (or which already exists?) that could be added to a custom page to allow the creation for a simple search for such things the way Kartik has done? I’m thinking of something along the lines of `<?php get_search_form(); ?>` which can be added to 404 page templates to allow the addition of a search box on such a page to get the user moving in the right direction.

This type of `original-of` search functionality could also be added to a simple widget as well so that one doesn’t need an entire page for it. Suggested verbiage: “Have a social media permalink for a piece of content? Use it here to search for the original version on this site.”

(Originally published at: http://boffosocko.com/2018/04/05/syndication-links-feature-idea-ui-code-to-create-an-original-of-page-andor-widget/)

**Comment by dshanske** [comment]
Completed in latest version. Text should be added in the theme or in the widget.
