### ISSUE TITLE
More options for argument 'style' in function 'get_syndication_links'

### ISSUE THREAD

**Issue by chrisbergr** [dshanske/syndication-links#81]
Hi David,

at first I'd like to mention that it seems there is a missing `</span>` in $after at `/includes/class-syn-meta.php:521`.

```
case 'p':
	$before = '<p class="' . $r['container-css'] . '"><span>';
	$sep    = ' ';
	$after  = '</p>';
	break;
```

I'm very thankful for this function that give me the possibility to implement it directly into my theme. The only thing I'm missing is an inline element aside the three block elements to be able to wrap the whole thing into e.g. a `<p>` element.

I'd suggest the following:

```
case 'span':
	$before = '<span class="' . $r['container-css'] . '">';
	$sep    = ' ';
	$after  = '</span>';
	break;
```

Maybe you can add this in your next version?

Best, Chris

**Comment by dshanske** [comment]
Will do

**Comment by dshanske** [comment]
Fixed this one.
