### ISSUE TITLE
remove_filter for content does not work

### ISSUE THREAD

**Issue by chrisbergr** [dshanske/syndication-links#82]
Hello again,

it seems like your mentioned way to prevent the plugin to automatically add the links to the content `remove_filter( 'the_content', array( 'Syn_Config', 'the_content' ), 30 )` does not work. 

Tested this on a live page running the recent official wordpress version and local with the recent nightly build beta version.

I've compared this with the code where you add the filter, but I'm not able to figure out the problem.

BTW: I've also mentioned that after unchecking the setting `Show on Front Page, Archive Pages, and Search Results`, the unordered list still apears, just with empty link titles.
-Is this intended?

**Comment by dshanske** [comment]
that's strange. I remove the filter on my own site and add the links directly

**Comment by dshanske** [comment]
Let me look into this

**Comment by dshanske** [comment]
https://github.com/dshanske/twentysixteen-indieweb/blob/master/inc/plugin-support.php

**Comment by dshanske** [comment]
Will do some tests, but will work with you to fix

**Comment by dshanske** [comment]
Added this to the readme.
