### ISSUE TITLE
Errors on update to 3.8.0

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#83]
After updating to the most recent version 3.8.0 of Semantic Linkbacks I’m getting the following error in the Comments sections of both posts and pages:

`Warning: in_array() expects parameter 2 to be array, string given in htdocs/blog/wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-walker-comment.php on line 25`

It seems to be throwing the error the same number of times that there are comments on the post. Additionally the comments section is showing both the raw mentions and facepiled versions. I’ll have to test some additional posts, but it also seems to have changed some mentions that were previously moderated out to now be showing.

(Originally published at: https://boffosocko.com/2018/06/20/errors-on-update-to-3-8-0/)

**Comment by dshanske** [comment]
@chrisaldrich Save the webmention settings page

**Comment by chrisaldrich** [comment]
Gah... and this was a semantic linkbacks bit and not a syndications link piece anyway...
