### ISSUE TITLE
Syntax error while installing on php 5.3

### ISSUE THREAD

**Issue by killerog** [dshanske/syndication-links#9]
This line: https://github.com/dshanske/syndication-links/blob/master/hcard-widget.php#L38 gives an error because of inline functions not being supported at php 5.3.29 apparently. Maybe change the required php version to install? Looks nicer than failing with an error :)

**Comment by dshanske** [comment]
Anonymous functions came in in PHP 5.3, so it should work. I'll add a function to detect lower than 5.3 and warn about it. 

What is the error exactly?

**Comment by killerog** [comment]
Hmm, I should've saved the error. Have upgraded my php in the meantime. It was someting like: unexpected T_FUNCTION expected )

**Comment by dshanske** [comment]
If you see it again, tell me. Function added regardless and will go in during the next push.

**Comment by killerog** [comment]
Tried to reproduce it on a different 5.3 subdomain, but won't work. Will let you know if I do.
