### ISSUE TITLE
Possible issue: no icon for mastodon-autopost (when it's not mastodon.social)

### ISSUE THREAD

**Issue by chrisbeckstrom** [dshanske/syndication-links#99]
Hey David et al! Thanks for your hard work on this!

I'm using Mastodon Autopost <https://github.com/simonfrey/mastodon_wordpress_autopost>. When I post to mastodon.social, the mastodon syndication link and mastodon icon show up below my post as expected. Example: <https://chrisbeckstrom.com/2018/12/31/website-broken-website-fixed/>

But if I post to my own fediverse instance (pleroma) running at <https://planet.chrisbeckstrom.com> the syndication link icon is just the generic "website" icon. example: <https://chrisbeckstrom.com/2019/01/07/33185/>

Tried editing `includes/simple-icons.php` by adding the line:
```
'mastodon' => 'Planet CB',
```
and also
```
'mastodon' => 'planet.chrisbeckstrom.com',
```
but that doesn't seem to do the trick.

Any idea how I can get the mastodon icon, or perhaps a custom icon, to work?
Thanks in advance!

**Comment by dshanske** [comment]
The problem is that the code has no easy way to map a custom domain to an icon. It uses the URL to try and figure it out. Let me see if I can pull the URL out of the Mastodon plugin...it must store it somewhere, and use it.

**Comment by dshanske** [comment]
Okay... found it in the code

**Comment by dshanske** [comment]
autopostToMastodon-instance

**Comment by chrisbeckstrom** [comment]
Cool, thanks David!

**Comment by dshanske** [comment]
Tried to add this in.
